<a href="https://colab.research.google.com/github/axmadovna17/week_2lab/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [2]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [4]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [5]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3],[4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [6]:
# TODO: Create a 3D tensor
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [7]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.7520, 0.9865, 0.2879, 0.9476],
        [0.8156, 0.6110, 0.2886, 0.3061],
        [0.3746, 0.5303, 0.3801, 0.0264],
        [0.8295, 0.0348, 0.3052, 0.9358]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [9]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(3, 224, 224)
random_tensor, random_tensor.dtype

print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [10]:
# TODO: Create zeros tensor
zeros = torch.zeros(5, 5)

print(zeros)
print(f"Shape: {zeros.shape}")

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Shape: torch.Size([5, 5])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [11]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)

print("Random Tensor:")
print(random_tensor)

print("\nOnes Like Tensor:")
print(ones_like)
print(f"Shape: {ones_like.shape}")

Random Tensor:
tensor([[0.6327, 0.6975, 0.7144],
        [0.5912, 0.6288, 0.2654],
        [0.2125, 0.2415, 0.4935]])

Ones Like Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Shape: torch.Size([3, 3])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [12]:
# TODO: Create range tensor
range_tensor = torch.arange(0, 21, 2)

print(range_tensor)
print(f"Shape: {range_tensor.shape}")

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
Shape: torch.Size([11])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [14]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

print("Float16 Tensor:")
print(float16_tensor)
print(f"Dtype: {float16_tensor.dtype}")

print("\nInt64 Tensor:")
print(int64_tensor)
print(f"Dtype: {int64_tensor.dtype}")

Float16 Tensor:
tensor([1., 2., 3.], dtype=torch.float16)
Dtype: torch.float16

Int64 Tensor:
tensor([1, 2, 3])
Dtype: torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [18]:
# TODO: Change dtype
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float32_tensor = float16_tensor.to(torch.float32)
print(float32_tensor )
print(f"Dtype: {float32_tensor.dtype}")

tensor([1., 2., 3.])
Dtype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [20]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)

print("Tensor:")
print(info_tensor)
print(f"Shape: {info_tensor.shape}")
print(f"Dtype: {info_tensor.dtype}")
print(f"Device: {info_tensor.device}")

Tensor:
tensor([[[0.2741, 0.8662, 0.3399, 0.1269],
         [0.8140, 0.6322, 0.1770, 0.7980],
         [0.7343, 0.3250, 0.4375, 0.8600]],

        [[0.0312, 0.0699, 0.5455, 0.1673],
         [0.1673, 0.4567, 0.6962, 0.6423],
         [0.6472, 0.4606, 0.2547, 0.8474]]])
Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [23]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor = tensor + 5

# TODO: Subtract 10
tensor = tensor - 10

# TODO: Multiply by 2
tensor = tensor * 2

# TODO: Divide by 10
tensor = tensor / 10

print(tensor)

tensor([1., 3., 5.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [24]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A, B)

# TODO: Matrix mul using @
result_at = A @ B

## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [26]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
min_val = agg_tensor.min()

# TODO: Max
max_val = agg_tensor.max()

# TODO: Mean (note: may need to cast to float)
mean_val = agg_tensor.float().mean()

# TODO: Sum
sum_val = agg_tensor.sum()

print(f"Min: {min_val}")
print(f"Max: {max_val}")
print(f"Mean: {mean_val}")
print(f"Sum: {sum_val}")

Min: 0
Max: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [27]:
# TODO: Argmin
min_index = agg_tensor.argmin()

# TODO: Argmax
max_index = agg_tensor.argmax()

print(f"Index of min value: {min_index}")
print(f"Index of max value: {max_index}")

Index of min value: 0
Index of max value: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [29]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)
print("Original Tensor:")
print(reshape_tensor)
print("Reshaped Tensor:")
print(reshaped)
print(f"Shape: {reshaped.shape}")

Original Tensor:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Reshaped Tensor:
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
Shape: torch.Size([2, 5])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [30]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
vertical_stack = torch.cat((tensor1, tensor2), dim=0)

# TODO: Stack horizontally (dim=1)
horizontal_stack = torch.cat((tensor1, tensor2), dim=1)
print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)

print("\nVertical Stack (dim=0):")
print(vertical_stack)
print(f"Shape: {vertical_stack.shape}")

print("\nHorizontal Stack (dim=1):")
print(horizontal_stack)
print(f"Shape: {horizontal_stack.shape}")

Tensor 1:
tensor([[0.6475, 0.2884],
        [0.9829, 0.5799]])

Tensor 2:
tensor([[0.4842, 0.9324],
        [0.9987, 0.1678]])

Vertical Stack (dim=0):
tensor([[0.6475, 0.2884],
        [0.9829, 0.5799],
        [0.4842, 0.9324],
        [0.9987, 0.1678]])
Shape: torch.Size([4, 2])

Horizontal Stack (dim=1):
tensor([[0.6475, 0.2884, 0.4842, 0.9324],
        [0.9829, 0.5799, 0.9987, 0.1678]])
Shape: torch.Size([2, 4])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [33]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()

# TODO: Unsqueeze on dim=0
unsqueezed = squeezed.unsqueeze(0)


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [35]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)
print("Permuted shape:", permuted.shape)

Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [37]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
value_5 = index_tensor[0, 1, 1]
# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]

## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [40]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print(from_numpy)
print(f"Dtype: {from_numpy.dtype}")

tensor([1, 2, 3, 4])
Dtype: torch.int64


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [41]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [42]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [43]:
# TODO: Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"Using device: {device}")

Using device: cpu


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [44]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)
print(f"Tensor on device: {gpu_tensor.device}")

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()
print("NumPy array:", cpu_numpy)

Tensor on device: cpu
NumPy array: [10 20 30]
